### ISSUE TITLE
Gnome 3.28 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by HFSARL** [l300lvl/XES-Settings-Center-Extension#6]
Hello,
I use Gnome 3.28 with Ubuntu 18.04 LTS and it's not work.  (No menu displayed)

Note that I had tested several months ago last year and that one of the previous versions seemed to have worked, maybe one of the recent changes?

Is it possible for me to do something to help make this beautiful extension work again?
If needed, i can provide virtual machine with :
- Ubuntu 18.04 LTS (Gnome 3.28)
- Ubuntu 16.04 LTS (Gnome 3.18)

Regards

Ref/Fork:
https://github.com/ChrisLauinger77/XES-Settings-Center-Extension

**Comment by ChrisLauinger77** [comment]
Did you try the version from my fork ?

**Comment by HFSARL** [comment]
I use your fork (last version) : 
git clone https://github.com/ChrisLauinger77/XES-Settings-Center-Extension
And copy folder " **SettingsCenter[at]xesnet.fr** " to ** /home/<user>/.local/share/gnome-shell/extensions/ **

I can see and enable extension with : gnome-shell-extension-prefs

But nothing in menu...

OS : Ubuntu 18.04 LTS (Gnome 3.28)

Regards

**Comment by ChrisLauinger77** [comment]
I see. 
I could not test it on 3.28. I can confirm it works on 3.30 and 3.32.

**Comment by ChrisLauinger77** [comment]
on https://extensions.gnome.org/extension/341/settingscenter/ somebody posted in the comments it works with Gnome 3.26.2.
What do you mean by nothing in menu ? Can you post a screenshot ?

**Comment by HFSARL** [comment]
The custom menu that appears normally is not displayed.

If needed, i can share a VM (vmware).

![Capture d’écran de 2019-09-10 07-03-15](https://user-images.githubusercontent.com/16742034/64562719-49048200-d399-11e9-9e12-a5435569e33b.png)

**Comment by ChrisLauinger77** [comment]
I compiled the gschema for gnome 3.30. maybe you need to do that for 3.28. 

glib-compile-schemas /home//.local/share/gnome-shell/extensions/SettingsCenter@xesnet.fr/schemas/
After that restart gnome-shell.

See also https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gio/glib-compile-schemas.html

**Comment by HFSARL** [comment]
`glib-compile-schemas /home/<userfolder>/.local/share/gnome-shell/extensions/SettingsCenter@xesnet.fr/schemas/
`
This command recreates the **gschemas.compiled**  file that has the same MD5 as the previous one.

**Comment by ChrisLauinger77** [comment]
I can have a look tomorrow if you provide a VM. What VM software is used ? Would need a KVM libvirt if possible.

**Comment by HFSARL** [comment]
Hello,

You can found a link for a virtual machine here : [LINK]


Have a nice day
Regards

**Comment by ChrisLauinger77** [comment]
I installed gnome-tweaks package inside the VM after I converted it to KVM/libvirt.
Found the bug and checked in the fix to my fork.
Please try it - should work now 4 u.
And french VM was quite a challenge. I had the language 4 years at school, but this was 25 years ago. Set it to english was harder then find the bug in the extension :D

**Comment by HFSARL** [comment]
Hello Chris,

New version Tested on :
3.18  # Ubuntu 16.04 LTS, works
3.28  # Ubuntu 18.04 LTS, works, It's awesome :)

Thank you for your work and maintain a fork of this extension   :+1: 
If you wish to speak "a little" French, you have my email, otherwise I can use the language of Shakespeare   ;-)

Have a nice day

**Comment by ChrisLauinger77** [comment]
Salut !

De rien mon ami.
I spare you the rest of my poor french. Have a good one.
